package controllers;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.paint.Color;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;
import java.util.Scanner;

import javafx.event.ActionEvent;
import javafx.scene.control.PasswordField;

public class SettingsController implements Initializable {

    @FXML
    private TextField tfPath;
    @FXML
    private TextField tfUsername;
    @FXML
    private PasswordField tfPwd;
    @FXML
    private Button btnSave;
    @FXML
    private Button btnDefaultSettings;

    @FXML
    private Label lblErrors;

    // Event Listener on Button[#btnDefaultSettings].onAction
    @FXML
    public void btnDefaultSettingsActionPerformed(ActionEvent event) {
            String path = "C:\\wamp\\bin\\mysql\\mysql5.6.12\\bin\\mysqldump.exe";
    
        tfPath.setText(path);
        tfUsername.setText("root");
        tfPwd.setText("");
    }
    // Event Listener on Button[#btnSave].onAction
    @FXML
    public void btnSaveActionPerformed(ActionEvent event) {
        // TODO Autogenerated
        lblErrors.setText("");
        lblErrors.setTextFill(Color.web("#ff6354"));

        String path = tfPath.getText();
        String username = tfUsername.getText().trim();
        String pwd = tfPwd.getText().trim();

        if (path.trim().isEmpty()) {
            //PATH CANNOT BE EMPTY
            lblErrors.setText("MYSQL DUMP PATH CANNOT BE EMPTY.");
            return;
        } else if (username.isEmpty()) {
            //USERNAME CANNOT BE EMPTY
            lblErrors.setText("MYSQL USERNAME CANNOT BE EMPTY.");
            return;
        }

        String output = path + ";" + username + ";" + pwd + ";";
        try {
            FileWriter writer = new FileWriter("mysqldump_path.txt", false);
            writer.write(output);
            writer.close();
            lblErrors.setTextFill(Color.web("#00FF00"));
            lblErrors.setText("SETTINGS SUCCESSFULLY SAVED.");

            //JOptionPane.showMessageDialog(this, "Path saved");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void initialize(URL location, ResourceBundle resources) {
        // TODO Auto-generated method stub
        lblErrors.setText("");

        String path;
        String mysql_username = "";
        String mysql_pwd = "";

        try {
            Scanner in = new Scanner(new File("mysqldump_path.txt"));
            path = in.nextLine();
            String username = "", pwd = "";
            String[] info = path.split(";");
            System.out.println("length :" + info.length);
            if (info.length == 2) {
                path = info[0];
                username = info[1];
            } else if (info.length == 3) {
                path = info[0];
                username = info[1];
                pwd = info[2];
            }
            tfPath.setText(path);
            tfUsername.setText(username);
            tfPwd.setText(pwd);
        } catch (Exception e) {
            path = "C:\\wamp\\bin\\mysql\\mysql5.6.12\\bin\\mysqldump.exe";
            tfPath.setText(path);
        }
    }
}
